<?php
// Woreda Officer: View Report
session_start();
require_once '../includes/db_connection.php';

// Language handling
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en';
}

if (isset($_GET['lang'])) {
    $_SESSION['lang'] = $_GET['lang'];
}

$lang = $_SESSION['lang'];

// Translations array
$translations = [
    'en' => [
        'title' => 'Woreda Vital Events Report',
        'report_title' => 'Woreda Vital Events Report',
        'comprehensive_analytics' => 'Comprehensive analytics and statistics for %s Woreda',
        'covering_x_kebeles' => 'Covering %d kebeles',
        'year_report' => 'Year %d Woreda Report',
        'print_full_report' => 'Print Full Report',
        'print_birth_report' => 'Print Birth Report',
        'print_marriage_report' => 'Print Marriage Report',
        'print_death_report' => 'Print Death Report',
        'print_divorce_report' => 'Print Divorce Report',
        'print_population_report' => 'Print Population Report',
        'estimated_population' => 'Estimated Population',
        'based_on_vital_events' => 'Based on vital events records',
        'births_minus_deaths' => '(Births: %s - Deaths: %s)',
        'total_births' => 'Total Births',
        'rate_per_1000' => 'Rate: %s per 1000',
        'high' => 'High',
        'low' => 'Low',
        'normal' => 'Normal',
        'total_deaths' => 'Total Deaths',
        'natural_increase' => 'Natural Increase',
        'growth_rate' => 'Growth Rate: %s%%',
        'growing' => 'Growing',
        'declining' => 'Declining',
        'stable' => 'Stable',
        'birth_to_death_ratio' => 'Birth to Death Ratio',
        'higher_ratio_indicates' => 'Higher ratio indicates population growth',
        'birth_rate' => 'Birth Rate',
        'per_1000_population' => 'Per 1000 population',
        'death_rate' => 'Death Rate',
        'approved' => 'Approved',
        'paid' => 'Paid',
        'pending' => 'Pending',
        'total_marriages' => 'Total Marriages',
        'total_divorces' => 'Total Divorces',
        'kebele_wise_statistics' => 'Kebele-wise Statistics',
        'kebele_name' => 'Kebele Name',
        'population' => 'Population',
        'births' => 'Births',
        'marriages' => 'Marriages',
        'deaths' => 'Deaths',
        'divorces' => 'Divorces',
        'total' => 'Total',
        'no_kebeles_found' => 'No kebeles found under this woreda.',
        'monthly_events_trend' => 'Monthly Events Trend - %d',
        'events_distribution' => 'Events Distribution',
        'recent_event_registrations' => 'Recent Event Registrations',
        'last_events_across_kebeles' => 'Last 10 events across all kebeles',
        'sno' => '#',
        'event_type' => 'Event Type',
        'name_main_info' => 'Name / Main Info',
        'kebele' => 'Kebele',
        'event_date' => 'Event Date',
        'status' => 'Status',
        'registered_at' => 'Registered At',
        'birth' => 'Birth',
        'marriage' => 'Marriage',
        'death' => 'Death',
        'divorce' => 'Divorce',
        'no_recent_events' => 'No recent events registered in your woreda.',
        'birth_events_register' => 'BIRTH EVENTS REGISTER - %s WOREDA',
        'covering_kebeles_population' => 'Covering %d Kebeles | Estimated Population: %s',
        'report_period' => 'Report Period',
        'generated_by_verms' => 'Generated by VERMS on %s',
        'birth_rate_label' => 'Birth Rate: %s per 1000',
        'child_name' => 'Child Name',
        'father_name' => 'Father Name',
        'mother_name' => 'Mother Name',
        'date_of_birth' => 'Date of Birth',
        'sex' => 'Sex',
        'registered_date' => 'Registered Date',
        'no_birth_records' => 'No birth records found',
        'population_demographic_report' => 'POPULATION AND DEMOGRAPHIC REPORT - %s WOREDA',
        'population_calculated_from_vital_events' => 'Population calculated from vital events',
        'population_summary' => 'POPULATION SUMMARY',
        'natural_increase_label' => 'Natural Increase',
        'vital_rates' => 'VITAL RATES',
        'birth_to_death_ratio_label' => 'Birth-to-Death Ratio',
        'marriage_rate' => 'Marriage Rate',
        'divorce_rate' => 'Divorce Rate',
        'kebele_wise_population_distribution' => 'KEBELE-WISE POPULATION DISTRIBUTION',
        'natural_increase_small' => 'Natural Increase',
        'growth_status' => 'Growth Status',
        'growing_small' => 'Growing',
        'declining_small' => 'Declining',
        'stable_small' => 'Stable',
        'population_source' => 'Population Source: Birth Records - Death Records',
        'husband_name' => 'Husband Name',
        'wife_name' => 'Wife Name',
        'marriage_date' => 'Marriage Date',
        'witness_1' => 'Witness 1',
        'witness_2' => 'Witness 2',
        'marriage_rate_label' => 'Marriage Rate: %s per 1000',
        'no_marriage_records' => 'No marriage records found',
        'deceased_name' => 'Deceased Name',
        'date_of_death' => 'Date of Death',
        'age' => 'Age',
        'cause_of_death' => 'Cause of Death',
        'death_rate_label' => 'Death Rate: %s per 1000',
        'no_death_records' => 'No death records found',
        'divorce_date' => 'Divorce Date',
        'divorce_rate_label' => 'Divorce Rate: %s per 1000',
        'no_divorce_records' => 'No divorce records found',
        'comprehensive_vital_events_register' => 'COMPREHENSIVE VITAL EVENTS REGISTER - %s WOREDA',
        'number_of_events' => 'Number of Events',
        'months' => 'Months',
        'logout' => 'Logout',
        'home' => 'Home',
        'profile' => 'Profile',
        'reports' => 'Reports',
        'settings' => 'Settings',
        'welcome' => 'Welcome',
        'copyright' => 'VERMS &copy; 2025. All rights reserved.',
        'dashboard' => 'Dashboard',
        'back_to_dashboard' => 'Back to Dashboard',
        'view_report' => 'View Report',
        'print' => 'Print'
    ],
    'am' => [
        'title' => 'የወረዳ ህይወት ክስተቶች ሪፖርት',
        'report_title' => 'የወረዳ ህይወት ክስተቶች ሪፖርት',
        'comprehensive_analytics' => 'ለ%s ወረዳ አጠቃላይ ትንተና እና ስታቲስቲክስ',
        'covering_x_kebeles' => '%d ቀበሌዎችን የሚያገለግል',
        'year_report' => 'ዓመት %d ወረዳ ሪፖርት',
        'print_full_report' => 'ሙሉ ሪፖርት አትም',
        'print_birth_report' => 'የትውልድ ሪፖርት አትም',
        'print_marriage_report' => 'የጋብቻ ሪፖርት አትም',
        'print_death_report' => 'የሞት ሪፖርት አትም',
        'print_divorce_report' => 'የፍቺ ሪፖርት አትም',
        'print_population_report' => 'የህዝብ ቁጥር ሪፖርት አትም',
        'estimated_population' => 'የሚገመተው ህዝብ ብዛት',
        'based_on_vital_events' => 'በህይወት ክስተቶች መዝገብ ላይ የተመሠረተ',
        'births_minus_deaths' => '(የተወለዱ: %s - የሞቱ: %s)',
        'total_births' => 'ጠቅላላ የተወለዱ',
        'rate_per_1000' => 'መጠን: %s በሺ',
        'high' => 'ከፍተኛ',
        'low' => 'ዝቅተኛ',
        'normal' => 'በመደበኛነት',
        'total_deaths' => 'ጠቅላላ የሞቱ',
        'natural_increase' => 'የተፈጥሮ ጭማሪ',
        'growth_rate' => 'የእድገት መጠን: %s%%',
        'growing' => 'በመጨመር ላይ',
        'declining' => 'በመቀነስ ላይ',
        'stable' => 'ቋሚ',
        'birth_to_death_ratio' => 'የትውልድ ወደ ሞት ሬሾ',
        'higher_ratio_indicates' => 'ከፍተኛ ሬሾ የህዝብ እድገትን ያመለክታል',
        'birth_rate' => 'የትውልድ መጠን',
        'per_1000_population' => 'በሺ ህዝብ',
        'death_rate' => 'የሞት መጠን',
        'approved' => 'የተፈቀደ',
        'paid' => 'የተከፈለ',
        'pending' => 'በመጠባበቅ ላይ',
        'total_marriages' => 'ጠቅላላ የተዋለዱ',
        'total_divorces' => 'ጠቅላላ የተፋቀሩ',
        'kebele_wise_statistics' => 'በቀበሌ የተመደቡ ስታቲስቲክስ',
        'kebele_name' => 'የቀበሌ ስም',
        'population' => 'ህዝብ',
        'births' => 'የተወለዱ',
        'marriages' => 'የተዋለዱ',
        'deaths' => 'የሞቱ',
        'divorces' => 'የተፋቀሩ',
        'total' => 'ጠቅላላ',
        'no_kebeles_found' => 'በዚህ ወረዳ ውስጥ ቀበሌዎች አልተገኙም።',
        'monthly_events_trend' => 'የወርሃዊ ክስተቶች አዝማሚያ - %d',
        'events_distribution' => 'የክስተቶች ስርጭት',
        'recent_event_registrations' => 'የቅርብ ጊዜ የክስተት ምዝገባዎች',
        'last_events_across_kebeles' => 'በሁሉም ቀበሌዎች ያሉ የመጨረሻ 10 ክስተቶች',
        'sno' => '#',
        'event_type' => 'የክስተት አይነት',
        'name_main_info' => 'ስም / ዋና መረጃ',
        'kebele' => 'ቀበሌ',
        'event_date' => 'የክስተት ቀን',
        'status' => 'ሁኔታ',
        'registered_at' => 'የተመዘገበው በ',
        'birth' => 'ትውልድ',
        'marriage' => 'ጋብቻ',
        'death' => 'ሞት',
        'divorce' => 'ፍቺ',
        'no_recent_events' => 'በወረዳዎ ውስጥ የቅርብ ጊዜ ክስተቶች አልተመዘገቡም።',
        'birth_events_register' => 'የትውልድ ክስተቶች ምዝገባ - %s ወረዳ',
        'covering_kebeles_population' => '%d ቀበሌዎችን የሚያገለግል | የሚገመተው ህዝብ: %s',
        'report_period' => 'የሪፖርት ጊዜ',
        'generated_by_verms' => 'በቪ.ኢ.አር.ኤም.ኤስ በ%s ተፈጥሯል',
        'birth_rate_label' => 'የትውልድ መጠን: %s በሺ',
        'child_name' => 'የልጅ ስም',
        'father_name' => 'የአባት ስም',
        'mother_name' => 'የእናት ስም',
        'date_of_birth' => 'የትውልድ ቀን',
        'sex' => 'ጾታ',
        'registered_date' => 'የተመዘገበበት ቀን',
        'no_birth_records' => 'የትውልድ ምዝገባዎች አልተገኙም',
        'population_demographic_report' => 'የህዝብ ብዛት እና ዲሞግራፊክ ሪፖርት - %s ወረዳ',
        'population_calculated_from_vital_events' => 'ህዝብ ብዛት ከህይወት ክስተቶች የተሰላ',
        'population_summary' => 'የህዝብ ብዛት ማጠቃለያ',
        'natural_increase_label' => 'የተፈጥሮ ጭማሪ',
        'vital_rates' => 'የህይወት ክስተቶች መጠኖች',
        'birth_to_death_ratio_label' => 'የትውልድ-ሞት ሬሾ',
        'marriage_rate' => 'የጋብቻ መጠን',
        'divorce_rate' => 'የፍቺ መጠን',
        'kebele_wise_population_distribution' => 'በቀበሌ የህዝብ ብዛት ስርጭት',
        'natural_increase_small' => 'ተፈጥሮዊ ጭማሪ',
        'growth_status' => 'የእድገት ሁኔታ',
        'growing_small' => 'በመጨመር ላይ',
        'declining_small' => 'በመቀነስ ላይ',
        'stable_small' => 'ቋሚ',
        'population_source' => 'ህዝብ ምንጭ: የትውልድ መዝገቦች - የሞት መዝገቦች',
        'husband_name' => 'የባለቤት ስም',
        'wife_name' => 'የሚስት ስም',
        'marriage_date' => 'የጋብቻ ቀን',
        'witness_1' => 'እምነተኛ 1',
        'witness_2' => 'እምነተኛ 2',
        'marriage_rate_label' => 'የጋብቻ መጠን: %s በሺ',
        'no_marriage_records' => 'የጋብቻ ምዝገባዎች አልተገኙም',
        'deceased_name' => 'የሞተው ስም',
        'date_of_death' => 'የሞት ቀን',
        'age' => 'እድሜ',
        'cause_of_death' => 'የሞት ምክንያት',
        'death_rate_label' => 'የሞት መጠን: %s በሺ',
        'no_death_records' => 'የሞት ምዝገባዎች አልተገኙም',
        'divorce_date' => 'የፍቺ ቀን',
        'divorce_rate_label' => 'የፍቺ መጠን: %s በሺ',
        'no_divorce_records' => 'የፍቺ ምዝገባዎች አልተገኙም',
        'comprehensive_vital_events_register' => 'አጠቃላይ የህይወት ክስተቶች ምዝገባ - %s ወረዳ',
        'number_of_events' => 'የክስተቶች ብዛት',
        'months' => 'ወራት',
        'logout' => 'ውጣ',
        'home' => 'መነሻ',
        'profile' => 'መገለጫ',
        'reports' => 'ሪፖርቶች',
        'settings' => 'ቅንብሮች',
        'welcome' => 'እንኳን ደህና መጡ',
        'copyright' => 'ቪ.ኢ.አር.ኤም.ኤስ &copy; 2025. መብቱ በህግ የተጠበቀ ነው።',
        'dashboard' => 'ዳሽቦርድ',
        'back_to_dashboard' => 'ወደ ዳሽቦርድ ተመለስ',
        'view_report' => 'ሪፖርት አይት',
        'print' => 'አትም'
    ]
];

function t($key, $params = []) {
    global $lang, $translations;
    $text = $translations[$lang][$key] ?? $translations['en'][$key] ?? $key;
    if (!empty($params)) {
        $text = vsprintf($text, $params);
    }
    return $text;
}

if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'woreda') {
    header('Location: ../login.php');
    exit();
}

// Get woreda ID for logged-in officer
$user_id = intval($_SESSION['user_id']);
$woreda_row = $conn->query(
    "SELECT id, woreda_name FROM woredas WHERE woreda_officer_id = $user_id"
)->fetch_assoc();
$woreda_id = $woreda_row ? $woreda_row['id'] : 0;
$woreda_name = $woreda_row ? $woreda_row['woreda_name'] : '';

// Get kebeles under this woreda
$kebeles = $conn->query("SELECT id, kebele_name FROM kebeles WHERE woreda_id = $woreda_id");
$kebele_ids = [];
while ($kebele = $kebeles->fetch_assoc()) {
    $kebele_ids[] = $kebele['id'];
}

// If no kebeles found, use empty array
$kebele_ids_in = empty($kebele_ids) ? '(-1)' : '(' . implode(',', $kebele_ids) . ')';

// Calculate total population from birth records (births minus deaths)
$total_births = $conn->query("SELECT COUNT(*) as total FROM birth_events WHERE place_of_birth IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$total_deaths = $conn->query("SELECT COUNT(*) as total FROM death_events WHERE place_of_death IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$total_population = max(0, $total_births - $total_deaths); // Ensure population doesn't go negative

// Fetch summary counts for the woreda (all kebeles under it)
// Births
$birth_count = $conn->query("SELECT COUNT(*) AS total FROM birth_events WHERE place_of_birth IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$birth_approved = $conn->query("SELECT COUNT(*) AS total FROM birth_events WHERE place_of_birth IN $kebele_ids_in AND status = 'Approved'")->fetch_assoc()['total'] ?? 0;
$birth_pending = $conn->query("SELECT COUNT(*) AS total FROM birth_events WHERE place_of_birth IN $kebele_ids_in AND status = 'Pending'")->fetch_assoc()['total'] ?? 0;
$birth_paid = $conn->query("SELECT COUNT(*) AS total FROM birth_events WHERE place_of_birth IN $kebele_ids_in AND status = 'Paid'")->fetch_assoc()['total'] ?? 0;

// Fetch all birth records for printable table
$birth_records = $conn->query("
    SELECT be.child_name, be.father_full_name, be.mother_full_name, be.date_of_birth, be.sex, be.status, be.created_at, k.kebele_name
    FROM birth_events be
    JOIN kebeles k ON be.place_of_birth = k.id
    WHERE be.place_of_birth IN $kebele_ids_in
    ORDER BY be.created_at DESC
");

// Marriages
$marriage_count = $conn->query("SELECT COUNT(*) AS total FROM marriage_events WHERE place_of_marriage IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$marriage_approved = $conn->query("SELECT COUNT(*) AS total FROM marriage_events WHERE place_of_marriage IN $kebele_ids_in AND status = 'Approved'")->fetch_assoc()['total'] ?? 0;
$marriage_pending = $conn->query("SELECT COUNT(*) AS total FROM marriage_events WHERE place_of_marriage IN $kebele_ids_in AND status = 'Pending'")->fetch_assoc()['total'] ?? 0;
$marriage_paid = $conn->query("SELECT COUNT(*) AS total FROM marriage_events WHERE place_of_marriage IN $kebele_ids_in AND status = 'Paid'")->fetch_assoc()['total'] ?? 0;

// Fetch all marriage records for printable table
$marriage_records = $conn->query("
    SELECT me.husband_name, me.wife_name, me.marriage_date, me.witness_1, me.witness_2, me.status, me.created_at, k.kebele_name
    FROM marriage_events me
    JOIN kebeles k ON me.place_of_marriage = k.id
    WHERE me.place_of_marriage IN $kebele_ids_in
    ORDER BY me.created_at DESC
");

// Deaths
$death_count = $conn->query("SELECT COUNT(*) AS total FROM death_events WHERE place_of_death IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$death_approved = $conn->query("SELECT COUNT(*) AS total FROM death_events WHERE place_of_death IN $kebele_ids_in AND status = 'Approved'")->fetch_assoc()['total'] ?? 0;
$death_pending = $conn->query("SELECT COUNT(*) AS total FROM death_events WHERE place_of_death IN $kebele_ids_in AND status = 'Pending'")->fetch_assoc()['total'] ?? 0;
$death_paid = $conn->query("SELECT COUNT(*) AS total FROM death_events WHERE place_of_death IN $kebele_ids_in AND status = 'Paid'")->fetch_assoc()['total'] ?? 0;

// Fetch all death records for printable table
$death_records = $conn->query("
    SELECT de.deceased_name, de.date_of_death, de.age, de.cause_of_death, de.sex, de.status, de.created_at, k.kebele_name
    FROM death_events de
    JOIN kebeles k ON de.place_of_death = k.id
    WHERE de.place_of_death IN $kebele_ids_in
    ORDER BY de.created_at DESC
");

// Divorces
$divorce_count = $conn->query("SELECT COUNT(*) AS total FROM divorce_events WHERE place_of_divorce IN $kebele_ids_in")->fetch_assoc()['total'] ?? 0;
$divorce_approved = $conn->query("SELECT COUNT(*) AS total FROM divorce_events WHERE place_of_divorce IN $kebele_ids_in AND status = 'Approved'")->fetch_assoc()['total'] ?? 0;
$divorce_pending = $conn->query("SELECT COUNT(*) AS total FROM divorce_events WHERE place_of_divorce IN $kebele_ids_in AND status = 'Pending'")->fetch_assoc()['total'] ?? 0;
$divorce_paid = $conn->query("SELECT COUNT(*) AS total FROM divorce_events WHERE place_of_divorce IN $kebele_ids_in AND status = 'Paid'")->fetch_assoc()['total'] ?? 0;

// Fetch all divorce records for printable table
$divorce_records = $conn->query("
    SELECT de.husband_name, de.wife_name, de.divorce_date, de.witness_1, de.witness_2, de.status, de.created_at, k.kebele_name
    FROM divorce_events de
    JOIN kebeles k ON de.place_of_divorce = k.id
    WHERE de.place_of_divorce IN $kebele_ids_in
    ORDER BY de.created_at DESC
");

// Calculate birth and death ratios
$birth_rate = $total_population > 0 ? ($birth_count / $total_population) * 1000 : 0; // per 1000 population
$death_rate = $total_population > 0 ? ($death_count / $total_population) * 1000 : 0; // per 1000 population
$natural_increase = $birth_count - $death_count;
$growth_rate = $total_population > 0 ? (($birth_count - $death_count) / $total_population) * 100 : 0;

// Get kebele-wise statistics
$kebele_stats = [];
$kebeles_result = $conn->query("SELECT id, kebele_name FROM kebeles WHERE woreda_id = $woreda_id");
while ($kebele = $kebeles_result->fetch_assoc()) {
    $kebele_id = $kebele['id'];
    
    $births = $conn->query("SELECT COUNT(*) AS total FROM birth_events WHERE place_of_birth = $kebele_id")->fetch_assoc()['total'] ?? 0;
    $marriages = $conn->query("SELECT COUNT(*) AS total FROM marriage_events WHERE place_of_marriage = $kebele_id")->fetch_assoc()['total'] ?? 0;
    $deaths = $conn->query("SELECT COUNT(*) AS total FROM death_events WHERE place_of_death = $kebele_id")->fetch_assoc()['total'] ?? 0;
    $divorces = $conn->query("SELECT COUNT(*) AS total FROM divorce_events WHERE place_of_divorce = $kebele_id")->fetch_assoc()['total'] ?? 0;
    
    // Calculate population for this kebele (births minus deaths)
    $kebele_population = max(0, $births - $deaths);
    
    $kebele_stats[] = [
        'name' => $kebele['kebele_name'],
        'population' => $kebele_population,
        'births' => $births,
        'marriages' => $marriages,
        'deaths' => $deaths,
        'divorces' => $divorces,
        'total' => $births + $marriages + $deaths + $divorces
    ];
}

// Monthly data for charts
$current_year = date('Y');
$monthly_data = [];

for ($month = 1; $month <= 12; $month++) {
    $month_start = date('Y-m-01', strtotime("$current_year-$month-01"));
    $month_end = date('Y-m-t', strtotime("$current_year-$month-01"));
    
    // Births
    $monthly_births = $conn->query("
        SELECT COUNT(*) as count FROM birth_events 
        WHERE place_of_birth IN $kebele_ids_in
        AND created_at BETWEEN '$month_start' AND '$month_end'
    ")->fetch_assoc()['count'] ?? 0;
    
    // Marriages
    $monthly_marriages = $conn->query("
        SELECT COUNT(*) as count FROM marriage_events 
        WHERE place_of_marriage IN $kebele_ids_in
        AND created_at BETWEEN '$month_start' AND '$month_end'
    ")->fetch_assoc()['count'] ?? 0;
    
    // Deaths
    $monthly_deaths = $conn->query("
        SELECT COUNT(*) as count FROM death_events 
        WHERE place_of_death IN $kebele_ids_in
        AND created_at BETWEEN '$month_start' AND '$month_end'
    ")->fetch_assoc()['count'] ?? 0;
    
    // Divorces
    $monthly_divorces = $conn->query("
        SELECT COUNT(*) as count FROM divorce_events 
        WHERE place_of_divorce IN $kebele_ids_in
        AND created_at BETWEEN '$month_start' AND '$month_end'
    ")->fetch_assoc()['count'] ?? 0;
    
    $monthly_data[] = [
        'month' => date('M', strtotime("$current_year-$month-01")),
        'births' => $monthly_births,
        'marriages' => $monthly_marriages,
        'deaths' => $monthly_deaths,
        'divorces' => $monthly_divorces
    ];
}

// Fetch last 10 events for table display
$recent_events = [];
foreach ([
    ['birth_events', 'Birth', 'child_name', 'date_of_birth', 'status'],
    ['marriage_events', 'Marriage', 'husband_name', 'marriage_date', 'status'],
    ['death_events', 'Death', 'deceased_name', 'date_of_death', 'status'],
    ['divorce_events', 'Divorce', 'husband_name', 'divorce_date', 'status']
] as $event) {
    [$table, $etype, $name_col, $date_col, $status_col] = $event;
    $events = $conn->query("
        SELECT e.id, '$etype' AS event_type, e.$name_col AS main_name, e.$date_col AS event_date, e.$status_col AS status, e.created_at, k.kebele_name
        FROM $table e
        JOIN kebeles k ON e.place_of_" . strtolower($etype) . " = k.id
        WHERE e.place_of_" . strtolower($etype) . " IN $kebele_ids_in
        ORDER BY e.created_at DESC
        LIMIT 10
    ");
    while ($row = $events->fetch_assoc()) $recent_events[] = $row;
}
// Sort recent_events by created_at DESC
usort($recent_events, fn($a, $b) => strtotime($b['created_at']) - strtotime($a['created_at']));
$recent_events = array_slice($recent_events, 0, 10);
?>
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <title><?= t('title') ?> - <?= htmlspecialchars($woreda_name) ?></title>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        :root {
            --primary-color: #2c3e50;
            --secondary-color: #3498db;
            --accent-color: #e74c3c;
            --success-color: #27ae60;
            --warning-color: #f39c12;
            --population-color: #9b59b6;
            --light-color: #ecf0f1;
            --dark-color: #2c3e50;
            --gradient-primary: linear-gradient(135deg, #2c3e50 0%, #3498db 100%);
            --gradient-secondary: linear-gradient(135deg, #3498db 0%, #2c3e50 100%);
            --gradient-population: linear-gradient(135deg, #9b59b6 0%, #3498db 100%);
            --shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            --transition: all 0.3s ease;
        }

        body {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            min-height: 100vh;
            font-family: <?= $lang === 'am' ? "'Ethiopia Jiret', 'Nyala', sans-serif" : "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif" ?>;
        }

        .dashboard-header {
            background: var(--gradient-primary);
            color: white;
            padding: 30px 0;
            margin-bottom: 30px;
            border-radius: 0 0 20px 20px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .dashboard-title {
            font-weight: 700;
            font-size: <?= $lang === 'am' ? '1.8rem' : '2.2rem' ?>;
            margin-bottom: 10px;
        }

        .dashboard-subtitle {
            font-size: <?= $lang === 'am' ? '1rem' : '1.1rem' ?>;
            opacity: 0.9;
        }

        .card {
            border: none;
            border-radius: 16px;
            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.08);
            transition: var(--transition);
            margin-bottom: 25px;
            overflow: hidden;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 12px 20px rgba(0, 0, 0, 0.12);
        }

        .card-header {
            background: var(--gradient-secondary);
            color: white;
            border: none;
            padding: 18px 25px;
            font-weight: 600;
            font-size: 1.3rem;
        }

        .card-body {
            padding: 25px;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }

        .stat-card {
            background: white;
            border-radius: 12px;
            padding: 20px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
            transition: var(--transition);
            border-left: 4px solid var(--secondary-color);
        }

        .stat-card:hover {
            transform: translateY(-3px);
            box-shadow: 0 8px 15px rgba(0, 0, 0, 0.15);
        }

        .stat-card.population {
            border-left-color: var(--population-color);
        }

        .stat-card.birth {
            border-left-color: var(--secondary-color);
        }

        .stat-card.death {
            border-left-color: var(--accent-color);
        }

        .stat-card.growth {
            border-left-color: var(--success-color);
        }

        .stat-icon {
            font-size: 2.5rem;
            margin-bottom: 15px;
        }

        .stat-number {
            font-size: 2.2rem;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .stat-label {
            font-size: 1rem;
            color: #6c757d;
            font-weight: 600;
            text-transform: uppercase;
        }

        .stat-subtext {
            font-size: 0.85rem;
            color: #6c757d;
            margin-top: 8px;
        }

        .population-source {
            font-size: 0.75rem;
            color: #95a5a6;
            margin-top: 5px;
            font-style: italic;
        }

        .rate-indicator {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 0.75rem;
            font-weight: 600;
            margin-left: 5px;
        }

        .rate-positive {
            background: rgba(39, 174, 96, 0.2);
            color: var(--success-color);
        }

        .rate-negative {
            background: rgba(231, 76, 60, 0.2);
            color: var(--accent-color);
        }

        .rate-neutral {
            background: rgba(149, 165, 166, 0.2);
            color: #95a5a6;
        }

        .chart-container {
            position: relative;
            height: 300px;
            margin-bottom: 20px;
        }

        .status-badge {
            padding: 6px 12px;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 600;
        }

        .status-pending {
            background: rgba(243, 156, 18, 0.2);
            color: var(--warning-color);
        }

        .status-paid {
            background: rgba(52, 152, 219, 0.2);
            color: var(--secondary-color);
        }

        .status-approved {
            background: rgba(39, 174, 96, 0.2);
            color: var(--success-color);
        }

        .event-badge {
            padding: 6px 12px;
            border-radius: 20px;
            font-size: 0.8rem;
            font-weight: 600;
            text-transform: uppercase;
        }

        .badge-birth {
            background: rgba(52, 152, 219, 0.2);
            color: var(--secondary-color);
        }

        .badge-marriage {
            background: rgba(155, 89, 182, 0.2);
            color: #9b59b6;
        }

        .badge-death {
            background: rgba(149, 165, 166, 0.2);
            color: #95a5a6;
        }

        .badge-divorce {
            background: rgba(231, 76, 60, 0.2);
            color: var(--accent-color);
        }

        .btn-print {
            background: var(--success-color);
            color: white;
            border: none;
            border-radius: 8px;
            padding: 10px 20px;
            font-weight: 500;
            transition: var(--transition);
        }

        .btn-print:hover {
            background: #219653;
            transform: translateY(-2px);
            box-shadow: 0 4px 8px rgba(33, 150, 83, 0.3);
        }

        .print-only {
            display: none;
        }
        
        /* Language switcher */
        .language-switcher {
            position: fixed;
            top: 80px;
            right: 20px;
            z-index: 1000;
            background: white;
            border-radius: 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            padding: 5px;
            display: flex;
            gap: 5px;
        }
        .lang-btn {
            border: none;
            padding: 5px 10px;
            border-radius: 15px;
            background: transparent;
            font-weight: 500;
            transition: all 0.3s ease;
            color: #2c3e50;
            font-size: 0.8rem;
            text-decoration: none;
            display: flex;
            align-items: center;
            gap: 3px;
        }
        .lang-btn.active {
            background: #0d6efd;
            color: white;
        }
        .lang-btn:hover:not(.active) {
            background: rgba(44, 62, 80, 0.1);
        }

        /* Print Styles */
        @media print {
            @page {
                size: A4 portrait;
                margin: 1cm;
            }
            
            body * {
                visibility: hidden;
                background: white !important;
                color: black !important;
            }
            
            .print-section, .print-section * {
                visibility: visible;
            }
            
            .print-section {
                position: absolute;
                left: 0;
                top: 0;
                width: 100%;
                background: white !important;
                padding: 0;
                margin: 0;
            }
            
            .no-print {
                display: none !important;
            }
            
            .print-only {
                display: block !important;
            }
            
            .card {
                box-shadow: none !important;
                border: 1px solid #ddd !important;
                margin-bottom: 15px;
            }
            
            .table {
                font-size: 10px;
                page-break-inside: avoid;
            }
            
            .table th {
                background-color: #f8f9fa !important;
                color: black !important;
                font-weight: bold;
                border: 1px solid #dee2e6;
            }
            
            .table td {
                border: 1px solid #dee2e6;
                padding: 6px 8px;
            }
            
            .report-header {
                border-bottom: 2px solid #333;
                margin-bottom: 15px;
                padding-bottom: 10px;
            }
            
            .badge {
                border: 1px solid #333;
                background: white !important;
                color: black !important;
                font-weight: bold;
            }
            
            h1, h2, h3, h4, h5, h6 {
                color: black !important;
                margin-bottom: 10px;
            }
            
            .text-muted {
                color: #666 !important;
            }
        }

        @media (max-width: 768px) {
            .dashboard-title {
                font-size: 1.8rem;
            }
            
            .card-body {
                padding: 15px;
            }
            
            .stats-grid {
                grid-template-columns: 1fr;
            }
            .language-switcher {
                top: 70px;
                right: 10px;
                padding: 4px;
            }
            .lang-btn {
                padding: 4px 8px;
                font-size: 0.75rem;
            }
        }

        @media (max-width: 576px) {
            .language-switcher {
                top: 60px;
                right: 5px;
                flex-direction: column;
                gap: 3px;
            }
            .lang-btn {
                padding: 3px 6px;
                font-size: 0.7rem;
            }
        }

        .table th {
            background-color: #f8f9fa;
            border-top: none;
            font-weight: 600;
            color: var(--primary-color);
            padding: 15px 12px;
            font-size: <?= $lang === 'am' ? '0.9rem' : '1rem' ?>;
        }

        .table td {
            padding: 15px 12px;
            vertical-align: middle;
            font-size: <?= $lang === 'am' ? '0.9rem' : '1rem' ?>;
        }

        .print-table {
            font-size: 11px;
        }

        .print-table th {
            background-color: #f8f9fa !important;
            color: #000 !important;
            font-weight: bold;
        }
        
        .report-header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 2px solid #dee2e6;
        }
        
        .kebele-badge {
            background: rgba(52, 152, 219, 0.1);
            color: #3498db;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: 600;
        }

        .ratio-card {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 12px;
            padding: 20px;
            text-align: center;
            margin-bottom: 20px;
        }

        .ratio-title {
            font-size: 1rem;
            margin-bottom: 10px;
            opacity: 0.9;
        }

        .ratio-value {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 5px;
        }

        .ratio-subtitle {
            font-size: 0.85rem;
            opacity: 0.8;
        }
        
        /* Font size adjustments for Amharic */
        .stat-label {
            font-size: <?= $lang === 'am' ? '0.85rem' : '1rem' ?>;
        }
        
        .stat-subtext {
            font-size: <?= $lang === 'am' ? '0.75rem' : '0.85rem' ?>;
        }
        
        .ratio-title {
            font-size: <?= $lang === 'am' ? '0.9rem' : '1rem' ?>;
        }
        
        .ratio-subtitle {
            font-size: <?= $lang === 'am' ? '0.75rem' : '0.85rem' ?>;
        }
    </style>
</head>
<body>
<?php 
// Update header include to pass translations
$GLOBALS['lang'] = $lang;
$GLOBALS['translations'] = $translations;
include_once __DIR__ . '/../includes/header.php'; 
?>

<!-- Language switcher -->
<div class="language-switcher no-print">
    <a href="?lang=en" class="lang-btn <?= $lang === 'en' ? 'active' : '' ?>">
        <i class="fas fa-globe-americas"></i> EN
    </a>
    <a href="?lang=am" class="lang-btn <?= $lang === 'am' ? 'active' : '' ?>">
        <i class="fas fa-globe-africa"></i> አማ
    </a>
</div>

<div class="dashboard-header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8">
                <h1 class="dashboard-title">
                    <i class="fas fa-chart-bar me-2"></i><?= t('report_title') ?>
                </h1>
                <p class="dashboard-subtitle">
                    <?= t('comprehensive_analytics', [htmlspecialchars($woreda_name)]) ?>
                    <br>
                    <small><?= t('covering_x_kebeles', [count($kebele_stats)]) ?></small>
                </p>
            </div>
            <div class="col-md-4 text-md-end">
                <div class="card bg-light" style="display: inline-block; padding: 15px 20px;">
                    <div class="d-flex align-items-center">
                        <div class="me-3">
                            <i class="fas fa-calendar-alt fa-2x text-primary"></i>
                        </div>
                        <div>
                            <h5 class="mb-0 text-dark"><?= t('year_report', [$current_year]) ?></h5>
                            <h3 class="mb-0 text-primary"><?= t('report_title') ?></h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <!-- Print Buttons -->
    <div class="row mb-4 no-print">
        <div class="col-12">
            <div class="d-flex gap-2 flex-wrap">
                <button class="btn btn-print" onclick="printReport('all')">
                    <i class="fas fa-print me-2"></i><?= t('print_full_report') ?>
                </button>
                <button class="btn btn-print" onclick="printReport('birth')">
                    <i class="fas fa-baby me-2"></i><?= t('print_birth_report') ?>
                </button>
                <button class="btn btn-print" onclick="printReport('marriage')">
                    <i class="fas fa-ring me-2"></i><?= t('print_marriage_report') ?>
                </button>
                <button class="btn btn-print" onclick="printReport('death')">
                    <i class="fas fa-book-dead me-2"></i><?= t('print_death_report') ?>
                </button>
                <button class="btn btn-print" onclick="printReport('divorce')">
                    <i class="fas fa-file-contract me-2"></i><?= t('print_divorce_report') ?>
                </button>
                <button class="btn btn-print" onclick="printReport('population')">
                    <i class="fas fa-users me-2"></i><?= t('print_population_report') ?>
                </button>
            </div>
        </div>
    </div>

    <!-- Population and Vital Statistics -->
    <div class="stats-grid no-print">
        <div class="stat-card population">
            <div class="stat-icon" style="color: #9b59b6;">
                <i class="fas fa-users"></i>
            </div>
            <div class="stat-number" style="color: #9b59b6;"><?= number_format($total_population) ?></div>
            <div class="stat-label"><?= t('estimated_population') ?></div>
            <div class="stat-subtext">
                <?= t('based_on_vital_events') ?>
            </div>
            <div class="population-source">
                <?= t('births_minus_deaths', [number_format($total_births), number_format($total_deaths)]) ?>
            </div>
        </div>

        <div class="stat-card birth">
            <div class="stat-icon text-primary">
                <i class="fas fa-baby"></i>
            </div>
            <div class="stat-number text-primary"><?= $birth_count ?></div>
            <div class="stat-label"><?= t('total_births') ?></div>
            <div class="stat-subtext">
                <?= t('rate_per_1000', [number_format($birth_rate, 2)]) ?>
                <?php if ($birth_rate > 20): ?>
                    <span class="rate-indicator rate-positive"><?= t('high') ?></span>
                <?php elseif ($birth_rate < 10): ?>
                    <span class="rate-indicator rate-negative"><?= t('low') ?></span>
                <?php else: ?>
                    <span class="rate-indicator rate-neutral"><?= t('normal') ?></span>
                <?php endif; ?>
            </div>
        </div>

        <div class="stat-card death">
            <div class="stat-icon text-danger">
                <i class="fas fa-book-dead"></i>
            </div>
            <div class="stat-number text-danger"><?= $death_count ?></div>
            <div class="stat-label"><?= t('total_deaths') ?></div>
            <div class="stat-subtext">
                <?= t('rate_per_1000', [number_format($death_rate, 2)]) ?>
            </div>
        </div>

        <div class="stat-card growth">
            <div class="stat-icon text-success">
                <i class="fas fa-chart-line"></i>
            </div>
            <div class="stat-number text-success"><?= $natural_increase ?></div>
            <div class="stat-label"><?= t('natural_increase') ?></div>
            <div class="stat-subtext">
                <?= t('growth_rate', [number_format($growth_rate, 2)]) ?>
                <?php if ($growth_rate > 0): ?>
                    <span class="rate-indicator rate-positive"><?= t('growing') ?></span>
                <?php elseif ($growth_rate < 0): ?>
                    <span class="rate-indicator rate-negative"><?= t('declining') ?></span>
                <?php else: ?>
                    <span class="rate-indicator rate-neutral"><?= t('stable') ?></span>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <!-- Birth/Death Ratio Cards -->
    <div class="row mb-4 no-print">
        <div class="col-md-4">
            <div class="ratio-card">
                <div class="ratio-title"><?= t('birth_to_death_ratio') ?></div>
                <div class="ratio-value">
                    <?= $death_count > 0 ? number_format($birth_count / $death_count, 2) : 'N/A' ?>:1
                </div>
                <div class="ratio-subtitle"><?= t('higher_ratio_indicates') ?></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="ratio-card" style="background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);">
                <div class="ratio-title"><?= t('birth_rate') ?></div>
                <div class="ratio-value"><?= number_format($birth_rate, 1) ?></div>
                <div class="ratio-subtitle"><?= t('per_1000_population') ?></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="ratio-card" style="background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);">
                <div class="ratio-title"><?= t('death_rate') ?></div>
                <div class="ratio-value"><?= number_format($death_rate, 1) ?></div>
                <div class="ratio-subtitle"><?= t('per_1000_population') ?></div>
            </div>
        </div>
    </div>

    <!-- Event Statistics -->
    <div class="stats-grid no-print">
        <div class="stat-card">
            <div class="stat-icon text-primary">
                <i class="fas fa-baby"></i>
            </div>
            <div class="stat-number text-primary"><?= $birth_count ?></div>
            <div class="stat-label"><?= t('total_births') ?></div>
            <div class="mt-2">
                <small class="text-success"><?= t('approved') ?>: <?= $birth_approved ?></small> |
                <small class="text-primary"><?= t('paid') ?>: <?= $birth_paid ?></small> |
                <small class="text-warning"><?= t('pending') ?>: <?= $birth_pending ?></small>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon" style="color: #9b59b6;">
                <i class="fas fa-ring"></i>
            </div>
            <div class="stat-number" style="color: #9b59b6;"><?= $marriage_count ?></div>
            <div class="stat-label"><?= t('total_marriages') ?></div>
            <div class="mt-2">
                <small class="text-success"><?= t('approved') ?>: <?= $marriage_approved ?></small> |
                <small class="text-primary"><?= t('paid') ?>: <?= $marriage_paid ?></small> |
                <small class="text-warning"><?= t('pending') ?>: <?= $marriage_pending ?></small>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon" style="color: #95a5a6;">
                <i class="fas fa-book-dead"></i>
            </div>
            <div class="stat-number" style="color: #95a5a6;"><?= $death_count ?></div>
            <div class="stat-label"><?= t('total_deaths') ?></div>
            <div class="mt-2">
                <small class="text-success"><?= t('approved') ?>: <?= $death_approved ?></small> |
                <small class="text-primary"><?= t('paid') ?>: <?= $death_paid ?></small> |
                <small class="text-warning"><?= t('pending') ?>: <?= $death_pending ?></small>
            </div>
        </div>

        <div class="stat-card">
            <div class="stat-icon text-danger">
                <i class="fas fa-file-contract"></i>
            </div>
            <div class="stat-number text-danger"><?= $divorce_count ?></div>
            <div class="stat-label"><?= t('total_divorces') ?></div>
            <div class="mt-2">
                <small class="text-success"><?= t('approved') ?>: <?= $divorce_approved ?></small> |
                <small class="text-primary"><?= t('paid') ?>: <?= $divorce_paid ?></small> |
                <small class="text-warning"><?= t('pending') ?>: <?= $divorce_pending ?></small>
            </div>
        </div>
    </div>

    <!-- Kebele-wise Statistics -->
    <div class="card no-print">
        <div class="card-header">
            <i class="fas fa-map-marker-alt me-2"></i><?= t('kebele_wise_statistics') ?>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><?= t('kebele_name') ?></th>
                            <th><?= t('population') ?></th>
                            <th><?= t('births') ?></th>
                            <th><?= t('marriages') ?></th>
                            <th><?= t('deaths') ?></th>
                            <th><?= t('divorces') ?></th>
                            <th><?= t('total') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($kebele_stats as $stat): ?>
                        <tr>
                            <td><strong><?= htmlspecialchars($stat['name']) ?></strong></td>
                            <td><?= number_format($stat['population']) ?></td>
                            <td><?= $stat['births'] ?></td>
                            <td><?= $stat['marriages'] ?></td>
                            <td><?= $stat['deaths'] ?></td>
                            <td><?= $stat['divorces'] ?></td>
                            <td><strong><?= $stat['total'] ?></strong></td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if (empty($kebele_stats)): ?>
                        <tr>
                            <td colspan="7" class="text-center text-muted py-4">
                                <i class="fas fa-exclamation-circle fa-2x mb-3 d-block"></i>
                                <?= t('no_kebeles_found') ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Charts Section -->
    <div class="row mb-5 no-print">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <i class="fas fa-chart-bar me-2"></i><?= t('monthly_events_trend', [$current_year]) ?>
                </div>
                <div class="card-body">
                    <div class="chart-container">
                        <canvas id="monthlyTrendChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <i class="fas fa-chart-pie me-2"></i><?= t('events_distribution') ?>
                </div>
                <div class="card-body">
                    <div class="chart-container">
                        <canvas id="distributionChart"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Events Table -->
    <div class="card no-print">
        <div class="card-header d-flex justify-content-between align-items-center">
            <div>
                <i class="fas fa-list me-2"></i><?= t('recent_event_registrations') ?>
            </div>
            <small class="text-muted"><?= t('last_events_across_kebeles') ?></small>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th><?= t('sno') ?></th>
                            <th><?= t('event_type') ?></th>
                            <th><?= t('name_main_info') ?></th>
                            <th><?= t('kebele') ?></th>
                            <th><?= t('event_date') ?></th>
                            <th><?= t('status') ?></th>
                            <th><?= t('registered_at') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=1; foreach($recent_events as $ev): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td>
                                <?php if ($ev['event_type'] === 'Birth'): ?>
                                    <span class="event-badge badge-birth">
                                        <i class="fas fa-baby me-1"></i><?= t('birth') ?>
                                    </span>
                                <?php elseif ($ev['event_type'] === 'Marriage'): ?>
                                    <span class="event-badge badge-marriage">
                                        <i class="fas fa-ring me-1"></i><?= t('marriage') ?>
                                    </span>
                                <?php elseif ($ev['event_type'] === 'Death'): ?>
                                    <span class="event-badge badge-death">
                                        <i class="fas fa-book-dead me-1"></i><?= t('death') ?>
                                    </span>
                                <?php elseif ($ev['event_type'] === 'Divorce'): ?>
                                    <span class="event-badge badge-divorce">
                                        <i class="fas fa-file-contract me-1"></i><?= t('divorce') ?>
                                    </span>
                                <?php endif; ?>
                            </td>
                            <td><strong><?= htmlspecialchars($ev['main_name']) ?></strong></td>
                            <td>
                                <span class="kebele-badge"><?= htmlspecialchars($ev['kebele_name']) ?></span>
                            </td>
                            <td><?= date('M j, Y', strtotime($ev['event_date'])) ?></td>
                            <td>
                                <?php if ($ev['status'] === 'Pending'): ?>
                                    <span class="status-badge status-pending"><?= $ev['status'] ?></span>
                                <?php elseif ($ev['status'] === 'Paid'): ?>
                                    <span class="status-badge status-paid"><?= $ev['status'] ?></span>
                                <?php elseif ($ev['status'] === 'Approved'): ?>
                                    <span class="status-badge status-approved"><?= $ev['status'] ?></span>
                                <?php else: ?>
                                    <span class="status-badge"><?= $ev['status'] ?></span>
                                <?php endif; ?>
                            </td>
                            <td>
                                <small class="text-muted">
                                    <?= date('M j, Y g:i A', strtotime($ev['created_at'])) ?>
                                </small>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        <?php if (empty($recent_events)): ?>
                        <tr>
                            <td colspan="7" class="text-center text-muted py-4">
                                <i class="fas fa-calendar-times fa-2x mb-3 d-block"></i>
                                <?= t('no_recent_events') ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Print Sections (Hidden by default) -->
<!-- Birth Report -->
<div class="print-section" id="printBirth" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('birth_events_register', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('covering_kebeles_population', [count($kebele_stats), number_format($total_population)]) ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>
        
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('child_name') ?></th>
                        <th><?= t('father_name') ?></th>
                        <th><?= t('mother_name') ?></th>
                        <th><?= t('date_of_birth') ?></th>
                        <th><?= t('sex') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('registered_date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($birth_records && $birth_records->num_rows > 0): ?>
                        <?php $i = 1; while($row = $birth_records->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['child_name']) ?></td>
                            <td><?= htmlspecialchars($row['father_full_name']) ?></td>
                            <td><?= htmlspecialchars($row['mother_full_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['date_of_birth'])) ?></td>
                            <td><?= htmlspecialchars($row['sex']) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['created_at'])) ?></td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="8" class="text-center"><?= t('no_birth_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('birth_rate_label', [number_format($birth_rate, 2)]) ?></small>
        </div>
    </div>
</div>

<!-- Population Report -->
<div class="print-section" id="printPopulation" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('population_demographic_report', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('population_calculated_from_vital_events') ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>

        <!-- Population Summary -->
        <h5 class="mt-4"><?= t('population_summary') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('total_births') ?></th>
                        <th><?= t('total_deaths') ?></th>
                        <th><?= t('estimated_population') ?></th>
                        <th><?= t('natural_increase_label') ?></th>
                        <th><?= t('growth_rate') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= number_format($total_births) ?></td>
                        <td><?= number_format($total_deaths) ?></td>
                        <td><strong><?= number_format($total_population) ?></strong></td>
                        <td><?= $natural_increase ?></td>
                        <td><?= number_format($growth_rate, 2) ?>%</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Vital Rates -->
        <h5 class="mt-4"><?= t('vital_rates') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('birth_rate') ?></th>
                        <th><?= t('death_rate') ?></th>
                        <th><?= t('birth_to_death_ratio_label') ?></th>
                        <th><?= t('marriage_rate') ?></th>
                        <th><?= t('divorce_rate') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= number_format($birth_rate, 2) ?> <?= t('per_1000_population') ?></td>
                        <td><?= number_format($death_rate, 2) ?> <?= t('per_1000_population') ?></td>
                        <td><?= $death_count > 0 ? number_format($birth_count / $death_count, 2) : 'N/A' ?>:1</td>
                        <td><?= number_format(($marriage_count / $total_population) * 1000, 2) ?> <?= t('per_1000_population') ?></td>
                        <td><?= number_format(($divorce_count / $total_population) * 1000, 2) ?> <?= t('per_1000_population') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Kebele-wise Population -->
        <h5 class="mt-4"><?= t('kebele_wise_population_distribution') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('kebele_name') ?></th>
                        <th><?= t('population') ?></th>
                        <th><?= t('births') ?></th>
                        <th><?= t('deaths') ?></th>
                        <th><?= t('natural_increase_small') ?></th>
                        <th><?= t('growth_status') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($kebele_stats as $stat): 
                        $kebele_growth = $stat['births'] - $stat['deaths'];
                        $kebele_growth_rate = $stat['population'] > 0 ? ($kebele_growth / $stat['population']) * 100 : 0;
                    ?>
                    <tr>
                        <td><?= htmlspecialchars($stat['name']) ?></td>
                        <td><?= number_format($stat['population']) ?></td>
                        <td><?= $stat['births'] ?></td>
                        <td><?= $stat['deaths'] ?></td>
                        <td><?= $kebele_growth ?></td>
                        <td>
                            <?php if ($kebele_growth > 0): ?>
                                <span class="badge"><?= t('growing_small') ?></span>
                            <?php elseif ($kebele_growth < 0): ?>
                                <span class="badge"><?= t('declining_small') ?></span>
                            <?php else: ?>
                                <span class="badge"><?= t('stable_small') ?></span>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('population_source') ?></small>
        </div>
    </div>
</div>

<!-- Marriage Report -->
<div class="print-section" id="printMarriage" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('marriage_events_register', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('covering_kebeles_population', [count($kebele_stats), number_format($total_population)]) ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>
        
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('husband_name') ?></th>
                        <th><?= t('wife_name') ?></th>
                        <th><?= t('marriage_date') ?></th>
                        <th><?= t('witness_1') ?></th>
                        <th><?= t('witness_2') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('registered_date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($marriage_records && $marriage_records->num_rows > 0): ?>
                        <?php $i = 1; while($row = $marriage_records->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['husband_name']) ?></td>
                            <td><?= htmlspecialchars($row['wife_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['marriage_date'])) ?></td>
                            <td><?= htmlspecialchars($row['witness_1']) ?></td>
                            <td><?= htmlspecialchars($row['witness_2']) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['created_at'])) ?></td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="8" class="text-center"><?= t('no_marriage_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('marriage_rate_label', [number_format(($marriage_count / $total_population) * 1000, 2)]) ?></small>
        </div>
    </div>
</div>

<!-- Death Report -->
<div class="print-section" id="printDeath" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('death_events_register', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('covering_kebeles_population', [count($kebele_stats), number_format($total_population)]) ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>
        
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('deceased_name') ?></th>
                        <th><?= t('date_of_death') ?></th>
                        <th><?= t('age') ?></th>
                        <th><?= t('cause_of_death') ?></th>
                        <th><?= t('sex') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('registered_date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($death_records && $death_records->num_rows > 0): ?>
                        <?php $i = 1; while($row = $death_records->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['deceased_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['date_of_death'])) ?></td>
                            <td><?= htmlspecialchars($row['age']) ?></td>
                            <td><?= htmlspecialchars($row['cause_of_death']) ?></td>
                            <td><?= htmlspecialchars($row['sex']) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['created_at'])) ?></td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="8" class="text-center"><?= t('no_death_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('death_rate_label', [number_format($death_rate, 2)]) ?></small>
        </div>
    </div>
</div>

<!-- Divorce Report -->
<div class="print-section" id="printDivorce" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('divorce_events_register', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('covering_kebeles_population', [count($kebele_stats), number_format($total_population)]) ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>
        
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('husband_name') ?></th>
                        <th><?= t('wife_name') ?></th>
                        <th><?= t('divorce_date') ?></th>
                        <th><?= t('witness_1') ?></th>
                        <th><?= t('witness_2') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('registered_date') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($divorce_records && $divorce_records->num_rows > 0): ?>
                        <?php $i = 1; while($row = $divorce_records->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['husband_name']) ?></td>
                            <td><?= htmlspecialchars($row['wife_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['divorce_date'])) ?></td>
                            <td><?= htmlspecialchars($row['witness_1']) ?></td>
                            <td><?= htmlspecialchars($row['witness_2']) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['created_at'])) ?></td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="8" class="text-center"><?= t('no_divorce_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('divorce_rate_label', [number_format(($divorce_count / $total_population) * 1000, 2)]) ?></small>
        </div>
    </div>
</div>

<!-- Full Report -->
<div class="print-section" id="printAll" style="display: none;">
    <div class="container-fluid">
        <div class="report-header">
            <h2><?= t('comprehensive_vital_events_register', [htmlspecialchars($woreda_name)]) ?></h2>
            <h5><?= t('covering_kebeles_population', [count($kebele_stats), number_format($total_population)]) ?></h5>
            <p class="text-muted mb-0"><?= t('report_period') ?>: <?= date('F j, Y') ?></p>
        </div>

        <!-- Population Summary -->
        <h5 class="mt-4"><?= t('population_summary') ?> (<?= t('population_calculated_from_vital_events') ?>)</h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('total_births') ?></th>
                        <th><?= t('total_deaths') ?></th>
                        <th><?= t('estimated_population') ?></th>
                        <th><?= t('natural_increase_label') ?></th>
                        <th><?= t('growth_rate') ?></th>
                        <th><?= t('birth_rate') ?></th>
                        <th><?= t('death_rate') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?= number_format($total_births) ?></td>
                        <td><?= number_format($total_deaths) ?></td>
                        <td><?= number_format($total_population) ?></td>
                        <td><?= $natural_increase ?></td>
                        <td><?= number_format($growth_rate, 2) ?>%</td>
                        <td><?= number_format($birth_rate, 2) ?> <?= t('per_1000_population') ?></td>
                        <td><?= number_format($death_rate, 2) ?> <?= t('per_1000_population') ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Birth Events -->
        <h5 class="mt-4"><?= strtoupper(t('birth')) ?> <?= t('events') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('child_name') ?></th>
                        <th><?= t('father_name') ?></th>
                        <th><?= t('date_of_birth') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('status') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $birth_records_all = $conn->query("
                        SELECT be.child_name, be.father_full_name, be.date_of_birth, be.status, k.kebele_name 
                        FROM birth_events be
                        JOIN kebeles k ON be.place_of_birth = k.id
                        WHERE be.place_of_birth IN $kebele_ids_in 
                        ORDER BY be.created_at DESC
                    ");
                    if ($birth_records_all && $birth_records_all->num_rows > 0): ?>
                        <?php $i = 1; while($row = $birth_records_all->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['child_name']) ?></td>
                            <td><?= htmlspecialchars($row['father_full_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['date_of_birth'])) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td>
                                <span class="badge"><?= $row['status'] ?></span>
                            </td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center"><?= t('no_birth_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- Marriage Events -->
        <h5 class="mt-4"><?= strtoupper(t('marriage')) ?> <?= t('events') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('husband_name') ?></th>
                        <th><?= t('wife_name') ?></th>
                        <th><?= t('marriage_date') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('status') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $marriage_records_all = $conn->query("
                        SELECT me.husband_name, me.wife_name, me.marriage_date, me.status, k.kebele_name 
                        FROM marriage_events me
                        JOIN kebeles k ON me.place_of_marriage = k.id
                        WHERE me.place_of_marriage IN $kebele_ids_in 
                        ORDER BY me.created_at DESC
                    ");
                    if ($marriage_records_all && $marriage_records_all->num_rows > 0): ?>
                        <?php $i = 1; while($row = $marriage_records_all->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['husband_name']) ?></td>
                            <td><?= htmlspecialchars($row['wife_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['marriage_date'])) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td>
                                <span class="badge"><?= $row['status'] ?></span>
                            </td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center"><?= t('no_marriage_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- Death Events -->
        <h5 class="mt-4"><?= strtoupper(t('death')) ?> <?= t('events') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('deceased_name') ?></th>
                        <th><?= t('date_of_death') ?></th>
                        <th><?= t('age') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('status') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $death_records_all = $conn->query("
                        SELECT de.deceased_name, de.date_of_death, de.age, de.status, k.kebele_name 
                        FROM death_events de
                        JOIN kebeles k ON de.place_of_death = k.id
                        WHERE de.place_of_death IN $kebele_ids_in 
                        ORDER BY de.created_at DESC
                    ");
                    if ($death_records_all && $death_records_all->num_rows > 0): ?>
                        <?php $i = 1; while($row = $death_records_all->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['deceased_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['date_of_death'])) ?></td>
                            <td><?= htmlspecialchars($row['age']) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td>
                                <span class="badge"><?= $row['status'] ?></span>
                            </td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center"><?= t('no_death_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <!-- Divorce Events -->
        <h5 class="mt-4"><?= strtoupper(t('divorce')) ?> <?= t('events') ?></h5>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th><?= t('sno') ?></th>
                        <th><?= t('husband_name') ?></th>
                        <th><?= t('wife_name') ?></th>
                        <th><?= t('divorce_date') ?></th>
                        <th><?= t('kebele') ?></th>
                        <th><?= t('status') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $divorce_records_all = $conn->query("
                        SELECT de.husband_name, de.wife_name, de.divorce_date, de.status, k.kebele_name 
                        FROM divorce_events de
                        JOIN kebeles k ON de.place_of_divorce = k.id
                        WHERE de.place_of_divorce IN $kebele_ids_in 
                        ORDER BY de.created_at DESC
                    ");
                    if ($divorce_records_all && $divorce_records_all->num_rows > 0): ?>
                        <?php $i = 1; while($row = $divorce_records_all->fetch_assoc()): ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['husband_name']) ?></td>
                            <td><?= htmlspecialchars($row['wife_name']) ?></td>
                            <td><?= date('M j, Y', strtotime($row['divorce_date'])) ?></td>
                            <td><?= htmlspecialchars($row['kebele_name']) ?></td>
                            <td>
                                <span class="badge"><?= $row['status'] ?></span>
                            </td>
                        </tr>
                        <?php endwhile; ?>
                    <?php else: ?>
                        <tr>
                            <td colspan="6" class="text-center"><?= t('no_divorce_records') ?></td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <div class="mt-4 text-muted">
            <small><?= t('generated_by_verms', [date('F j, Y \a\t g:i A')]) ?> | <?= t('population_source') ?></small>
        </div>
    </div>
</div>

<?php 
// Update footer include to pass translations
$GLOBALS['lang'] = $lang;
$GLOBALS['translations'] = $translations;
include '../includes/footer.php'; 
?>
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js'></script>
<script>
// Save language preference
document.addEventListener('DOMContentLoaded', function() {
    const lang = '<?= $lang ?>';
    localStorage.setItem('preferred_lang', lang);
});

// Monthly Trend Chart - Bar Chart
const monthlyCtx = document.getElementById('monthlyTrendChart').getContext('2d');
const monthlyChart = new Chart(monthlyCtx, {
    type: 'bar',
    data: {
        labels: <?= json_encode(array_column($monthly_data, 'month')) ?>,
        datasets: [
            {
                label: '<?= t('births') ?>',
                data: <?= json_encode(array_column($monthly_data, 'births')) ?>,
                backgroundColor: 'rgba(52, 152, 219, 0.8)',
                borderColor: '#3498db',
                borderWidth: 1
            },
            {
                label: '<?= t('marriages') ?>',
                data: <?= json_encode(array_column($monthly_data, 'marriages')) ?>,
                backgroundColor: 'rgba(155, 89, 182, 0.8)',
                borderColor: '#9b59b6',
                borderWidth: 1
            },
            {
                label: '<?= t('deaths') ?>',
                data: <?= json_encode(array_column($monthly_data, 'deaths')) ?>,
                backgroundColor: 'rgba(149, 165, 166, 0.8)',
                borderColor: '#95a5a6',
                borderWidth: 1
            },
            {
                label: '<?= t('divorces') ?>',
                data: <?= json_encode(array_column($monthly_data, 'divorces')) ?>,
                backgroundColor: 'rgba(231, 76, 60, 0.8)',
                borderColor: '#e74c3c',
                borderWidth: 1
            }
        ]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            title: {
                display: true,
                text: '<?= t('monthly_events_trend', [$current_year]) ?>'
            }
        },
        scales: {
            y: {
                beginAtZero: true,
                title: {
                    display: true,
                    text: '<?= t('number_of_events') ?>'
                }
            },
            x: {
                title: {
                    display: true,
                    text: '<?= t('months') ?>'
                }
            }
        }
    }
});

// Distribution Chart
const distCtx = document.getElementById('distributionChart').getContext('2d');
const distChart = new Chart(distCtx, {
    type: 'doughnut',
    data: {
        labels: ['<?= t('births') ?>', '<?= t('marriages') ?>', '<?= t('deaths') ?>', '<?= t('divorces') ?>'],
        datasets: [{
            data: [<?= $birth_count ?>, <?= $marriage_count ?>, <?= $death_count ?>, <?= $divorce_count ?>],
            backgroundColor: [
                '#3498db',
                '#9b59b6',
                '#95a5a6',
                '#e74c3c'
            ],
            borderWidth: 2,
            borderColor: '#fff'
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                position: 'bottom'
            },
            title: {
                display: true,
                text: '<?= t('events_distribution') ?>'
            }
        }
    }
});

// Print functionality
function printReport(type) {
    // Hide all print sections first
    document.querySelectorAll('.print-section').forEach(section => {
        section.style.display = 'none';
    });
    
    // Show the selected print section
    const printSection = document.getElementById(`print${type.charAt(0).toUpperCase() + type.slice(1)}`);
    if (printSection) {
        printSection.style.display = 'block';
    }
    
    // Print the document
    window.print();
    
    // Hide the print section after printing
    setTimeout(() => {
        if (printSection) {
            printSection.style.display = 'none';
        }
    }, 500);
}
</script>
</body>
</html>